language: python
python:
  - "3.7"
install:
  - pip install -r test-requirements.txt
  - mkdir -p symlinks
  - ln -s /usr/bin/gcc-6 symlinks/gcc
  - ln -s /usr/bin/gcov-6 symlinks/gcov
script:
  - export PATH=$PWD/symlinks:$PATH
  - flake8 .
  - python -m unittest discover tests
  - python setup.py sdist bdist_wheel
  - pip install dist/firefox_code_coverage-1.0.0.tar.gz
cache: pip
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
